services:
  - type: web
    name: osland-global-network
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn osland.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "osland-global-network.onrender.com"
      - key: DB_PATH
        value: "/data/db.sqlite3"
    disk:
      name: osland-db
      mountPath: /data
      sizeGB: 1
