# Generated by Django 6.0.4 on 2026-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aboutpage_company_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_section_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
